name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: build
      run: ./build.sh

  tests:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: build
      run: ./build.sh
    - name: criterion
      run: sudo add-apt-repository ppa:snaipewastaken/ppa && sudo apt-get install criterion-dev
    - name: AVTests
      run: cd tests/ && g++ AVTests.cpp -l criterion -I ../inc/ -I ../inc/Parser ../src/Core.cpp ../src/Parser/File.cpp && mv a.out .. && cd .. && ./a.out
